---
- hosts: all
  become: true

  tasks:
    - name: Install Git
      package:
        name: git
        state: present

    - name: Install Nginx
      package:
        name: nginx
        state: present
    - name: Start nginx
      service:
         name: nginx
         state: started
    - name: Install apache2 httpd
      package:
        name: apache2
        state: latest
    - name: start apache2 httpd
      service:
        name: apache2
        state: started
        enabled: yes
      become: yes
